 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace ChatC2S
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Login_Request = (Nettention.Proud.RmiID)1000+1;
			public const Nettention.Proud.RmiID SendMsg = (Nettention.Proud.RmiID)1000+2;
			public const Nettention.Proud.RmiID ChannelMsg = (Nettention.Proud.RmiID)1000+3;
			public const Nettention.Proud.RmiID ChannelJoin = (Nettention.Proud.RmiID)1000+4;
			public const Nettention.Proud.RmiID ChannelLeave = (Nettention.Proud.RmiID)1000+5;
			public const Nettention.Proud.RmiID GetChannelList_Request = (Nettention.Proud.RmiID)1000+6;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Login_Request,
			SendMsg,
			ChannelMsg,
			ChannelJoin,
			ChannelLeave,
			GetChannelList_Request,
		};
	}
}
namespace ChatS2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Login_Response = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID SendMsg = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID ChannelMsg = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID GetChannelList_Response = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID Event_Filtering = (Nettention.Proud.RmiID)2000+5;
			public const Nettention.Proud.RmiID Event_Notice = (Nettention.Proud.RmiID)2000+6;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Login_Response,
			SendMsg,
			ChannelMsg,
			GetChannelList_Response,
			Event_Filtering,
			Event_Notice,
		};
	}
}






				 
