 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace ClientToLogin
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Login_Request = (Nettention.Proud.RmiID)12000+1;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Login_Request,
		};
	}
}
namespace LoginToClient
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Login_Success = (Nettention.Proud.RmiID)13000+1;
			public const Nettention.Proud.RmiID Login_Failed = (Nettention.Proud.RmiID)13000+2;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Login_Success,
			Login_Failed,
		};
	}
}






				 
