 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace ClientToChat
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Connect_Request = (Nettention.Proud.RmiID)10000+1;
			public const Nettention.Proud.RmiID DirectMsg = (Nettention.Proud.RmiID)10000+2;
			public const Nettention.Proud.RmiID ChannelMsg = (Nettention.Proud.RmiID)10000+3;
			public const Nettention.Proud.RmiID ChannelJoin = (Nettention.Proud.RmiID)10000+4;
			public const Nettention.Proud.RmiID ChannelLeave = (Nettention.Proud.RmiID)10000+5;
			public const Nettention.Proud.RmiID GetChannelList_Request = (Nettention.Proud.RmiID)10000+6;
			public const Nettention.Proud.RmiID MsgTranslate = (Nettention.Proud.RmiID)10000+7;
			public const Nettention.Proud.RmiID MsgTranslate_auto = (Nettention.Proud.RmiID)10000+8;
			public const Nettention.Proud.RmiID MsgRecord_Channel = (Nettention.Proud.RmiID)10000+9;
			public const Nettention.Proud.RmiID MsgRecord_Direct = (Nettention.Proud.RmiID)10000+10;
			public const Nettention.Proud.RmiID MsgRecord_Notice = (Nettention.Proud.RmiID)10000+11;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Connect_Request,
			DirectMsg,
			ChannelMsg,
			ChannelJoin,
			ChannelLeave,
			GetChannelList_Request,
			MsgTranslate,
			MsgTranslate_auto,
			MsgRecord_Channel,
			MsgRecord_Direct,
			MsgRecord_Notice,
		};
	}
}
namespace ChatToClient
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Connect_Success = (Nettention.Proud.RmiID)11000+1;
			public const Nettention.Proud.RmiID Connect_Failed = (Nettention.Proud.RmiID)11000+2;
			public const Nettention.Proud.RmiID ChannelJoin_Success = (Nettention.Proud.RmiID)11000+3;
			public const Nettention.Proud.RmiID ChannelJoin_Failed = (Nettention.Proud.RmiID)11000+4;
			public const Nettention.Proud.RmiID ChannelLeave_Success = (Nettention.Proud.RmiID)11000+5;
			public const Nettention.Proud.RmiID ChannelLeave_Failed = (Nettention.Proud.RmiID)11000+6;
			public const Nettention.Proud.RmiID DirectMsg = (Nettention.Proud.RmiID)11000+7;
			public const Nettention.Proud.RmiID ChannelMsg = (Nettention.Proud.RmiID)11000+8;
			public const Nettention.Proud.RmiID GetChannelList_Response = (Nettention.Proud.RmiID)11000+9;
			public const Nettention.Proud.RmiID Event_Filtering = (Nettention.Proud.RmiID)11000+10;
			public const Nettention.Proud.RmiID Event_Notice = (Nettention.Proud.RmiID)11000+11;
			public const Nettention.Proud.RmiID MsgTranslate_Success = (Nettention.Proud.RmiID)11000+12;
			public const Nettention.Proud.RmiID MsgTranslate_Failed = (Nettention.Proud.RmiID)11000+13;
			public const Nettention.Proud.RmiID MsgRecord_Success = (Nettention.Proud.RmiID)11000+14;
			public const Nettention.Proud.RmiID MsgRecord_Failed = (Nettention.Proud.RmiID)11000+15;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Connect_Success,
			Connect_Failed,
			ChannelJoin_Success,
			ChannelJoin_Failed,
			ChannelLeave_Success,
			ChannelLeave_Failed,
			DirectMsg,
			ChannelMsg,
			GetChannelList_Response,
			Event_Filtering,
			Event_Notice,
			MsgTranslate_Success,
			MsgTranslate_Failed,
			MsgRecord_Success,
			MsgRecord_Failed,
		};
	}
}






				 
