
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "ClientToLoginLink_common.h"
namespace ClientToLogin {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_Login_Request,
	};

	int g_RmiIDListCount = 1;

}


namespace LoginToClient {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_Login_Success,
               
		Rmi_Login_Failed,
	};

	int g_RmiIDListCount = 2;

}





